apiVersion: v1
kind: Service
metadata:                     
  name: api-gestion-paises-service
  labels:                   
    app: api-gestion-paises-demo
spec:                         
  type: LoadBalancer 
  selector:
    app: api-gestion-paises-demo
  ports:
  - name: http
    port: 8082
    targetPort: 8082