apiVersion: v1
kind: Service
metadata:                     
  name: api-gestion-paises-service
  labels:                   
    app: api-gestion-paises-demo
spec:                         
  type: NodePort 
  selector:
    app: api-gestion-paises-demo
  ports:
  - name: http
    port: 8083
    targetPort: 8083