apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gestion-paises-deployment-secret
  namespace: dev
  labels:
    app: api-gestion-paises-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gestion-paises-secret
  template:
    metadata:
      labels:
        app: api-gestion-paises-secret
    spec:
      containers:
      - name: api-gestion-paises-demo
        image: anovoa1975/ms-demo-v7:1.0.0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8084
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-user-secret-jc
                key: rootUsername
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-secret-jc
                key: rootPassword