apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-deployment
  namespace: dev
  labels:
    app: srv-db-mysql
spec:
  selector:
    matchLabels:
      name: db-mysql
      app: srv-db-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      name: srv-db-mysql
      labels:
        name: db-mysql
        app: srv-db-mysql
    spec:
      containers:
      - image: mysql:9.1.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret-jc
              key: rootPassword
        ports:
        - containerPort: 3306     
          name: mysql
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: kbvolume
      volumes:
      - name: kbvolume
        persistentVolumeClaim:
          claimName: mipvc